[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
waggle-mvb = "6a2VeLtBtKAYu5ftup9o9uLEvfySdEzBhSDukHFZaopu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/huybuidac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./prebuilt-programs/metaplex_token_metadata.so"
