[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
waggle-mvb = "DaeRkRvTZrFjQPKF6XdGok5XbhFBUSHukqQUvhygQ9pm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./prebuilt-programs/metaplex_token_metadata.so"
